class JsonConvertTemplates {
  static const String emptyContent = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by json_convert_generator package
// Do not modify this file as it will be overwritten on the next build

typedef JsonConvertFunction<T> = T Function(Map<String, dynamic> json);
typedef JsonConvertListFunction =
		List<dynamic> Function(List<Map<String, dynamic>> data);
typedef ConvertExceptionHandler =
		void Function(Object error, StackTrace stackTrace);

final JsonConvert jsonConvert = JsonConvert();

class JsonConvert {
	static ConvertExceptionHandler? onError;
	JsonConvertHelper convertHelper = JsonConvertHelper();

	static T? fromJsonAsT<T>(dynamic json) {
		return null;
	}
}

class JsonConvertHelper {
	final Map<String, JsonConvertFunction> convertFuncMap = {};
	final Map<String, JsonConvertListFunction> listConvertFuncMap = {};
}
''';

  static const String content = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by json_convert_generator package
// Do not modify this file as it will be overwritten on the next build

{{imports}}

typedef JsonConvertFunction<T> = T Function(Map<String, dynamic> json);
typedef JsonConvertListFunction =
		List<dynamic> Function(List<Map<String, dynamic>> data);
typedef ConvertExceptionHandler =
		void Function(Object error, StackTrace stackTrace);

final JsonConvert jsonConvert = JsonConvert();

class JsonConvert {
	static ConvertExceptionHandler? onError;
	JsonConvertHelper convertHelper = JsonConvertHelper();

	static T? fromJsonAsT<T>(dynamic json) {
		if (json == null) {
			return null;
		}
		if (json is T) {
			return json;
		}
		try {
			if (json is List) {
				return jsonConvert._convertList<T>(
					json.map((dynamic e) => e as Map<String, dynamic>).toList(),
				);
			} else {
				return jsonConvert._convert<T>(json);
			}
		} catch (e, stackTrace) {
			return jsonConvert._onConvertError<T?>(e, stackTrace, null);
		}
	}

	T? _convert<T>(dynamic value) {
		final String type = T.toString();
		final String normalizedType = type.endsWith('?')
				? type.substring(0, type.length - 1)
				: type;
		final String valueS = value.toString();
		if (normalizedType == "String") {
			return valueS as T;
		} else if (normalizedType == "int") {
			final int? intValue = int.tryParse(valueS);
			if (intValue == null) {
				return double.tryParse(valueS)?.toInt() as T?;
			} else {
				return intValue as T;
			}
		} else if (normalizedType == "double") {
			return double.parse(valueS) as T;
		} else if (normalizedType == "DateTime") {
			return DateTime.parse(valueS) as T;
		} else if (normalizedType == "bool") {
			if (valueS == '0' || valueS == '1') {
				return (valueS == '1') as T;
			}
			return (valueS == 'true') as T;
		} else if (normalizedType == "Map" || normalizedType.startsWith("Map<")) {
			return value as T;
		} else {
			final covertFunc = convertHelper.convertFuncMap[normalizedType];
			if (covertFunc == null) {
				throw UnimplementedError(
					"\$type unimplemented,you can try running the app again",
				);
			}
			final mapValue = value is Map<String, dynamic>
					? value
					: Map<String, dynamic>.from(value as Map);
			return covertFunc(mapValue) as T;
		}
	}

	T? _convertList<T>(List<Map<String, dynamic>> data) {
		final String type = T.toString();
		final String normalizedType = type.endsWith('?')
				? type.substring(0, type.length - 1)
				: type;
		final listConvertFunc = convertHelper.listConvertFuncMap[normalizedType];
		if (listConvertFunc == null) {
			throw UnimplementedError(
				"\$type unimplemented,you can try running the app again",
			);
		}
		return listConvertFunc(data) as T?;
	}

	T _onConvertError<T>(Object error, StackTrace stackTrace, T fallback) {
		if (onError != null) {
			onError!(error, stackTrace);
		}
		return fallback;
	}
}

class JsonConvertHelper {
	final Map<String, JsonConvertListFunction> listConvertFuncMap = {
{{listEntries}}
	};

	final Map<String, JsonConvertFunction> convertFuncMap = {
{{convertEntries}}
	};

	bool containsKey(String type) {
		return convertFuncMap.containsKey(type);
	}

	JsonConvertFunction? operator [](String key) {
		return convertFuncMap[key];
	}
}
''';

  static const String genericListEntry = '''
		(List<{{className}}>).toString(): (List<Map<String, dynamic>> data) => data
				.map<{{className}}>(
					(Map<String, dynamic> e) => {{className}}.fromJson(e, (json) => json),
				)
				.toList(),''';

  static const String nonGenericListEntry = '''
		(List<{{className}}>).toString(): (List<Map<String, dynamic>> data) => data
				.map<{{className}}>(
					(Map<String, dynamic> e) => {{className}}.fromJson(e),
				)
				.toList(),''';

  static const String genericConvertEntry = '''
		({{className}}).toString(): (Map<String, dynamic> json) =>
				{{className}}.fromJson(json, (data) => data),''';

  static const String nonGenericConvertEntry =
      '    ({{className}}).toString(): {{className}}.fromJson,';
}
